import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Techbook9ja',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
     <ClerkProvider>
      <html lang="en">
        <body className='bg-cyan-100'>{children}</body>
      </html>
    </ClerkProvider>
  )
}
